add registration logic (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧
yana617/pharmacy-api pull request #5
Opened 2020-11-02 13:15 UTC by DaryaSht

2020-12-05 21:42 UTC, yana617 requested changes

2020-12-05 21:42 UTC, yana617 commented on database/models/admin.js
> + module.exports = { Admin };
Не надо так делать, здесь экспортится только схема, верни как было

2020-12-05 21:42 UTC, yana617 commented on routes/admin.js
> +          return res.status(500).json('crypt crashed gen salt');
никогда не возвращай строчку

```suggestion
return res.status(500).json({
  success: false,
  message: 'crypt crashed while generating salt',
});
```

2020-12-05 21:42 UTC, yana617 commented on routes/admin.js
> +      res.status(500).json({ error: e.message });
{ success: false, message: e.message }

2020-12-05 21:42 UTC, yana617 commented on routes/admin.js
> +const { Admin } = require('../database/models/admin');
const Admin = require('../database/models/admin');

2020-12-05 21:42 UTC, yana617 commented on routes/admin.js
> +        return res.status(403).json({ message: 'Incorrect token' });
`return res.status(403).json({ success: false, message: 'Incorrect token' });`

2020-12-05 21:42 UTC, yana617 commented on routes/admin.js
> +        return res.status(400).json({ message: 'User with this login already exists' });
success: false

2020-12-05 21:42 UTC, yana617 commented on routes/admin.js
> +      await bcrypt.genSalt(10, (err, salt) => {
Я говорила использовать метод .pre
https://mongoosejs.com/docs/middleware.html#pre
Ты здесь проверив что все ок (токен верный, такого логина не существует) - сохраняешь документ. А уже в файле модельки пишешь мидлварку для добавления хэша/соли к обьекту. Только проверь `document.isNew` в .pre, потому что оно вызывается и при обновлении документа, а не только добавлении. (тебе нельзя менять хэш/соль при изменении логина, к примеру)

2020-12-05 21:42 UTC, yana617 commented on routes/admin.js
> +
Добавь строчку 
`// TODO: remove after testing`

2021-02-13 15:10 UTC, yana617 approved these changes

2021-02-17 07:15 UTC, DaryaSht commented
The best Pull request I have ever seen

2021-02-17 07:15 UTC, merged